apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-pv
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
