apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport-svc
spec:
  selector:
    app: mongodb # Cambiar por la etiqueta correcta utilizada en el archivo deployment.yaml
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  type: NodePort
